/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module control_unit(i_clk, ni_rst, \inst[0] , \inst[1] , \inst[2] , \inst[3] , \inst[4] , \inst[5] , \inst[6] , \inst[7] , \inst[8] , \inst[9] , \inst[10] , \inst[11] , \inst[12] , \inst[13] , \inst[14] , \inst[15] , \inst[16] , \inst[17] , \inst[18] 
, \inst[19] , \inst[20] , \inst[21] , \inst[22] , \inst[23] , \inst[24] , \inst[25] , \inst[26] , \inst[27] , \inst[28] , \inst[29] , \inst[30] , \inst[31] , \rs1_data[0] , \rs1_data[1] , \rs1_data[2] , \rs1_data[3] , \rs1_data[4] , \rs1_data[5] , \rs1_data[6] , \rs1_data[7] 
, \rs1_data[8] , \rs1_data[9] , \rs1_data[10] , \rs1_data[11] , \rs1_data[12] , \rs1_data[13] , \rs1_data[14] , \rs1_data[15] , \rs1_data[16] , \rs1_data[17] , \rs1_data[18] , \rs1_data[19] , \rs1_data[20] , \rs1_data[21] , \rs1_data[22] , \rs1_data[23] , \rs1_data[24] , \rs1_data[25] , \rs1_data[26] , \rs1_data[27] , \rs1_data[28] 
, \rs1_data[29] , \rs1_data[30] , \rs1_data[31] , \vl_forwarded[0] , \vl_forwarded[1] , br_unsign, vector_enb, op1_sel, op2_sel, branch_signal, jmp_signal, scalar_wb, \alu_opcode[0] , \alu_opcode[1] , \alu_opcode[2] , \alu_opcode[3] , scalar_wren, mems_rden, mems_wren, is_vsetvli, \vlen_enb[0] 
, \vlen_enb[1] , \vlen_enb[2] , \vlen_enb[3] , \vlen_enb[4] , \vlen_enb[5] , \vlen_enb[6] , \vlen_enb[7] , \vlen_set[0] , \vlen_set[1] , \vlen_set[2] , \vlen_set[3] , \vlen_set[4] , \vlen_set[5] , \vlen_set[6] , \vlen_set[7] , \vlen_set[8] , \vlen_set[9] , \vlen_set[10] , \vlen_set[11] , \vlen_set[12] , \vlen_set[13] 
, \vlen_set[14] , \vlen_set[15] , \vlen_set[16] , \vlen_set[17] , \vlen_set[18] , \vlen_set[19] , \vlen_set[20] , \vlen_set[21] , \vlen_set[22] , \vlen_set[23] , \vlen_set[24] , \vlen_set[25] , \vlen_set[26] , \vlen_set[27] , \vlen_set[28] , \vlen_set[29] , \vlen_set[30] , \vlen_set[31] );
  input i_clk;
  wire i_clk;
  input ni_rst;
  wire ni_rst;
  input \inst[0] ;
  wire \inst[0] ;
  input \inst[1] ;
  wire \inst[1] ;
  input \inst[2] ;
  wire \inst[2] ;
  input \inst[3] ;
  wire \inst[3] ;
  input \inst[4] ;
  wire \inst[4] ;
  input \inst[5] ;
  wire \inst[5] ;
  input \inst[6] ;
  wire \inst[6] ;
  input \inst[7] ;
  wire \inst[7] ;
  input \inst[8] ;
  wire \inst[8] ;
  input \inst[9] ;
  wire \inst[9] ;
  input \inst[10] ;
  wire \inst[10] ;
  input \inst[11] ;
  wire \inst[11] ;
  input \inst[12] ;
  wire \inst[12] ;
  input \inst[13] ;
  wire \inst[13] ;
  input \inst[14] ;
  wire \inst[14] ;
  input \inst[15] ;
  wire \inst[15] ;
  input \inst[16] ;
  wire \inst[16] ;
  input \inst[17] ;
  wire \inst[17] ;
  input \inst[18] ;
  wire \inst[18] ;
  input \inst[19] ;
  wire \inst[19] ;
  input \inst[20] ;
  wire \inst[20] ;
  input \inst[21] ;
  wire \inst[21] ;
  input \inst[22] ;
  wire \inst[22] ;
  input \inst[23] ;
  wire \inst[23] ;
  input \inst[24] ;
  wire \inst[24] ;
  input \inst[25] ;
  wire \inst[25] ;
  input \inst[26] ;
  wire \inst[26] ;
  input \inst[27] ;
  wire \inst[27] ;
  input \inst[28] ;
  wire \inst[28] ;
  input \inst[29] ;
  wire \inst[29] ;
  input \inst[30] ;
  wire \inst[30] ;
  input \inst[31] ;
  wire \inst[31] ;
  input \rs1_data[0] ;
  wire \rs1_data[0] ;
  input \rs1_data[1] ;
  wire \rs1_data[1] ;
  input \rs1_data[2] ;
  wire \rs1_data[2] ;
  input \rs1_data[3] ;
  wire \rs1_data[3] ;
  input \rs1_data[4] ;
  wire \rs1_data[4] ;
  input \rs1_data[5] ;
  wire \rs1_data[5] ;
  input \rs1_data[6] ;
  wire \rs1_data[6] ;
  input \rs1_data[7] ;
  wire \rs1_data[7] ;
  input \rs1_data[8] ;
  wire \rs1_data[8] ;
  input \rs1_data[9] ;
  wire \rs1_data[9] ;
  input \rs1_data[10] ;
  wire \rs1_data[10] ;
  input \rs1_data[11] ;
  wire \rs1_data[11] ;
  input \rs1_data[12] ;
  wire \rs1_data[12] ;
  input \rs1_data[13] ;
  wire \rs1_data[13] ;
  input \rs1_data[14] ;
  wire \rs1_data[14] ;
  input \rs1_data[15] ;
  wire \rs1_data[15] ;
  input \rs1_data[16] ;
  wire \rs1_data[16] ;
  input \rs1_data[17] ;
  wire \rs1_data[17] ;
  input \rs1_data[18] ;
  wire \rs1_data[18] ;
  input \rs1_data[19] ;
  wire \rs1_data[19] ;
  input \rs1_data[20] ;
  wire \rs1_data[20] ;
  input \rs1_data[21] ;
  wire \rs1_data[21] ;
  input \rs1_data[22] ;
  wire \rs1_data[22] ;
  input \rs1_data[23] ;
  wire \rs1_data[23] ;
  input \rs1_data[24] ;
  wire \rs1_data[24] ;
  input \rs1_data[25] ;
  wire \rs1_data[25] ;
  input \rs1_data[26] ;
  wire \rs1_data[26] ;
  input \rs1_data[27] ;
  wire \rs1_data[27] ;
  input \rs1_data[28] ;
  wire \rs1_data[28] ;
  input \rs1_data[29] ;
  wire \rs1_data[29] ;
  input \rs1_data[30] ;
  wire \rs1_data[30] ;
  input \rs1_data[31] ;
  wire \rs1_data[31] ;
  input \vl_forwarded[0] ;
  wire \vl_forwarded[0] ;
  input \vl_forwarded[1] ;
  wire \vl_forwarded[1] ;
  output br_unsign;
  wire br_unsign;
  output vector_enb;
  wire vector_enb;
  output op1_sel;
  wire op1_sel;
  output op2_sel;
  wire op2_sel;
  output branch_signal;
  wire branch_signal;
  output jmp_signal;
  wire jmp_signal;
  output scalar_wb;
  wire scalar_wb;
  output \alu_opcode[0] ;
  wire \alu_opcode[0] ;
  output \alu_opcode[1] ;
  wire \alu_opcode[1] ;
  output \alu_opcode[2] ;
  wire \alu_opcode[2] ;
  output \alu_opcode[3] ;
  wire \alu_opcode[3] ;
  output scalar_wren;
  wire scalar_wren;
  output mems_rden;
  wire mems_rden;
  output mems_wren;
  wire mems_wren;
  output is_vsetvli;
  wire is_vsetvli;
  output \vlen_enb[0] ;
  wire \vlen_enb[0] ;
  output \vlen_enb[1] ;
  wire \vlen_enb[1] ;
  output \vlen_enb[2] ;
  wire \vlen_enb[2] ;
  output \vlen_enb[3] ;
  wire \vlen_enb[3] ;
  output \vlen_enb[4] ;
  wire \vlen_enb[4] ;
  output \vlen_enb[5] ;
  wire \vlen_enb[5] ;
  output \vlen_enb[6] ;
  wire \vlen_enb[6] ;
  output \vlen_enb[7] ;
  wire \vlen_enb[7] ;
  output \vlen_set[0] ;
  wire \vlen_set[0] ;
  output \vlen_set[1] ;
  wire \vlen_set[1] ;
  output \vlen_set[2] ;
  wire \vlen_set[2] ;
  output \vlen_set[3] ;
  wire \vlen_set[3] ;
  output \vlen_set[4] ;
  wire \vlen_set[4] ;
  output \vlen_set[5] ;
  wire \vlen_set[5] ;
  output \vlen_set[6] ;
  wire \vlen_set[6] ;
  output \vlen_set[7] ;
  wire \vlen_set[7] ;
  output \vlen_set[8] ;
  wire \vlen_set[8] ;
  output \vlen_set[9] ;
  wire \vlen_set[9] ;
  output \vlen_set[10] ;
  wire \vlen_set[10] ;
  output \vlen_set[11] ;
  wire \vlen_set[11] ;
  output \vlen_set[12] ;
  wire \vlen_set[12] ;
  output \vlen_set[13] ;
  wire \vlen_set[13] ;
  output \vlen_set[14] ;
  wire \vlen_set[14] ;
  output \vlen_set[15] ;
  wire \vlen_set[15] ;
  output \vlen_set[16] ;
  wire \vlen_set[16] ;
  output \vlen_set[17] ;
  wire \vlen_set[17] ;
  output \vlen_set[18] ;
  wire \vlen_set[18] ;
  output \vlen_set[19] ;
  wire \vlen_set[19] ;
  output \vlen_set[20] ;
  wire \vlen_set[20] ;
  output \vlen_set[21] ;
  wire \vlen_set[21] ;
  output \vlen_set[22] ;
  wire \vlen_set[22] ;
  output \vlen_set[23] ;
  wire \vlen_set[23] ;
  output \vlen_set[24] ;
  wire \vlen_set[24] ;
  output \vlen_set[25] ;
  wire \vlen_set[25] ;
  output \vlen_set[26] ;
  wire \vlen_set[26] ;
  output \vlen_set[27] ;
  wire \vlen_set[27] ;
  output \vlen_set[28] ;
  wire \vlen_set[28] ;
  output \vlen_set[29] ;
  wire \vlen_set[29] ;
  output \vlen_set[30] ;
  wire \vlen_set[30] ;
  output \vlen_set[31] ;
  wire \vlen_set[31] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  INV_X1 _38_ (
    .A(\inst[6] ),
    .ZN(_00_)
  );
  INV_X1 _39_ (
    .A(\inst[4] ),
    .ZN(_01_)
  );
  INV_X1 _40_ (
    .A(\inst[12] ),
    .ZN(_02_)
  );
  INV_X1 _41_ (
    .A(\inst[13] ),
    .ZN(_03_)
  );
  INV_X1 _42_ (
    .A(\inst[14] ),
    .ZN(_04_)
  );
  INV_X1 _43_ (
    .A(\inst[5] ),
    .ZN(_05_)
  );
  NAND2_X1 _44_ (
    .A1(\inst[1] ),
    .A2(\inst[0] ),
    .ZN(_06_)
  );
  OR2_X1 _45_ (
    .A1(\inst[3] ),
    .A2(\inst[2] ),
    .ZN(_07_)
  );
  NOR3_X1 _46_ (
    .A1(\inst[6] ),
    .A2(_06_),
    .A3(_07_),
    .ZN(_08_)
  );
  NAND2_X1 _47_ (
    .A1(\inst[4] ),
    .A2(_08_),
    .ZN(_09_)
  );
  NOR2_X1 _48_ (
    .A1(\inst[12] ),
    .A2(\inst[14] ),
    .ZN(_10_)
  );
  NAND2_X1 _49_ (
    .A1(\inst[13] ),
    .A2(_10_),
    .ZN(_11_)
  );
  OR3_X1 _50_ (
    .A1(_02_),
    .A2(\inst[13] ),
    .A3(\inst[30] ),
    .ZN(_12_)
  );
  AOI21_X1 _51_ (
    .A(_04_),
    .B1(\inst[13] ),
    .B2(_02_),
    .ZN(_13_)
  );
  AOI22_X1 _52_ (
    .A1(\inst[13] ),
    .A2(_10_),
    .B1(_12_),
    .B2(_13_),
    .ZN(_14_)
  );
  NAND2_X1 _53_ (
    .A1(\inst[4] ),
    .A2(\inst[5] ),
    .ZN(_15_)
  );
  NOR4_X1 _54_ (
    .A1(\inst[12] ),
    .A2(\inst[13] ),
    .A3(\inst[14] ),
    .A4(_15_),
    .ZN(_16_)
  );
  NAND3_X1 _55_ (
    .A1(\inst[30] ),
    .A2(_08_),
    .A3(_16_),
    .ZN(_17_)
  );
  OAI22_X1 _56_ (
    .A1(_09_),
    .A2(_14_),
    .B1(_17_),
    .B2(\inst[25] ),
    .ZN(\alu_opcode[0] )
  );
  NAND3_X1 _57_ (
    .A1(_04_),
    .A2(\inst[5] ),
    .A3(\inst[25] ),
    .ZN(_18_)
  );
  NAND3_X1 _58_ (
    .A1(\inst[12] ),
    .A2(_03_),
    .A3(_18_),
    .ZN(_19_)
  );
  AOI21_X1 _59_ (
    .A(_09_),
    .B1(_11_),
    .B2(_19_),
    .ZN(\alu_opcode[1] )
  );
  NOR3_X1 _60_ (
    .A1(_00_),
    .A2(\inst[4] ),
    .A3(_05_),
    .ZN(_20_)
  );
  NOR4_X1 _61_ (
    .A1(\inst[4] ),
    .A2(_05_),
    .A3(_06_),
    .A4(_07_),
    .ZN(_21_)
  );
  INV_X1 _62_ (
    .A(_21_),
    .ZN(_22_)
  );
  NOR2_X1 _63_ (
    .A1(_00_),
    .A2(_22_),
    .ZN(branch_signal)
  );
  AOI21_X1 _64_ (
    .A(\inst[14] ),
    .B1(\inst[13] ),
    .B2(\inst[12] ),
    .ZN(_23_)
  );
  AOI211_X1 _65_ (
    .A(_09_),
    .B(_23_),
    .C1(\inst[13] ),
    .C2(\inst[14] ),
    .ZN(\alu_opcode[2] )
  );
  NOR2_X1 _66_ (
    .A1(\inst[6] ),
    .A2(_22_),
    .ZN(mems_wren)
  );
  AND3_X1 _67_ (
    .A1(_01_),
    .A2(_05_),
    .A3(_08_),
    .ZN(mems_rden)
  );
  NOR3_X1 _68_ (
    .A1(_03_),
    .A2(_04_),
    .A3(_09_),
    .ZN(\alu_opcode[3] )
  );
  NOR3_X1 _69_ (
    .A1(\inst[6] ),
    .A2(_01_),
    .A3(\inst[5] ),
    .ZN(_24_)
  );
  NAND3_X1 _70_ (
    .A1(\inst[4] ),
    .A2(_05_),
    .A3(_08_),
    .ZN(_25_)
  );
  NAND3_X1 _71_ (
    .A1(\inst[6] ),
    .A2(_03_),
    .A3(_21_),
    .ZN(_26_)
  );
  AND4_X1 _72_ (
    .A1(\inst[12] ),
    .A2(_03_),
    .A3(\inst[14] ),
    .A4(\inst[30] ),
    .ZN(_27_)
  );
  AOI21_X1 _73_ (
    .A(_27_),
    .B1(_10_),
    .B2(_03_),
    .ZN(_28_)
  );
  MUX2_X1 _74_ (
    .A(_28_),
    .B(_26_),
    .S(_25_),
    .Z(br_unsign)
  );
  NAND3_X1 _75_ (
    .A1(\inst[1] ),
    .A2(\inst[0] ),
    .A3(\inst[2] ),
    .ZN(_29_)
  );
  NOR2_X1 _76_ (
    .A1(\inst[3] ),
    .A2(_29_),
    .ZN(_30_)
  );
  NAND2_X1 _77_ (
    .A1(_00_),
    .A2(_01_),
    .ZN(_31_)
  );
  NAND3_X1 _78_ (
    .A1(\inst[6] ),
    .A2(\inst[4] ),
    .A3(_05_),
    .ZN(_32_)
  );
  AOI211_X1 _79_ (
    .A(\inst[3] ),
    .B(_29_),
    .C1(_31_),
    .C2(_32_),
    .ZN(vector_enb)
  );
  OR4_X1 _80_ (
    .A1(_02_),
    .A2(_03_),
    .A3(_04_),
    .A4(_32_),
    .ZN(_33_)
  );
  NOR3_X1 _81_ (
    .A1(\inst[3] ),
    .A2(_29_),
    .A3(_33_),
    .ZN(is_vsetvli)
  );
  AOI21_X1 _82_ (
    .A(_21_),
    .B1(vector_enb),
    .B2(_33_),
    .ZN(scalar_wren)
  );
  NOR4_X1 _83_ (
    .A1(_00_),
    .A2(\inst[4] ),
    .A3(_05_),
    .A4(_29_),
    .ZN(jmp_signal)
  );
  AOI22_X1 _84_ (
    .A1(_24_),
    .A2(_30_),
    .B1(jmp_signal),
    .B2(\inst[3] ),
    .ZN(_34_)
  );
  OAI21_X1 _85_ (
    .A(_34_),
    .B1(_22_),
    .B2(_00_),
    .ZN(op1_sel)
  );
  NOR2_X1 _86_ (
    .A1(\inst[6] ),
    .A2(_15_),
    .ZN(_35_)
  );
  OAI21_X1 _87_ (
    .A(_30_),
    .B1(_35_),
    .B2(_20_),
    .ZN(_36_)
  );
  AOI21_X1 _88_ (
    .A(_21_),
    .B1(_08_),
    .B2(_05_),
    .ZN(_37_)
  );
  NAND3_X1 _89_ (
    .A1(_34_),
    .A2(_36_),
    .A3(_37_),
    .ZN(op2_sel)
  );
  assign \vlen_set[15]  = 1'h0;
  assign \vlen_set[14]  = 1'h0;
  assign \vlen_set[13]  = 1'h0;
  assign \vlen_set[12]  = 1'h0;
  assign \vlen_set[11]  = 1'h0;
  assign \vlen_set[10]  = 1'h0;
  assign \vlen_set[9]  = 1'h0;
  assign \vlen_set[8]  = 1'h0;
  assign \vlen_set[7]  = 1'h0;
  assign \vlen_set[6]  = 1'h0;
  assign \vlen_set[5]  = 1'h0;
  assign \vlen_set[4]  = 1'h0;
  assign \vlen_set[3]  = 1'h1;
  assign \vlen_set[2]  = 1'h0;
  assign \vlen_set[1]  = 1'h0;
  assign \vlen_set[0]  = 1'h0;
  assign \vlen_enb[7]  = 1'h1;
  assign \vlen_enb[6]  = 1'h1;
  assign \vlen_enb[5]  = 1'h1;
  assign \vlen_enb[4]  = 1'h1;
  assign \vlen_enb[3]  = 1'h1;
  assign \vlen_enb[2]  = 1'h1;
  assign \vlen_enb[1]  = 1'h1;
  assign \vlen_enb[0]  = 1'h1;
  assign \vlen_set[16]  = 1'h0;
  assign \vlen_set[17]  = 1'h0;
  assign \vlen_set[18]  = 1'h0;
  assign \vlen_set[19]  = 1'h0;
  assign \vlen_set[20]  = 1'h0;
  assign \vlen_set[21]  = 1'h0;
  assign \vlen_set[22]  = 1'h0;
  assign \vlen_set[23]  = 1'h0;
  assign \vlen_set[24]  = 1'h0;
  assign \vlen_set[25]  = 1'h0;
  assign \vlen_set[26]  = 1'h0;
  assign \vlen_set[27]  = 1'h0;
  assign \vlen_set[28]  = 1'h0;
  assign \vlen_set[29]  = 1'h0;
  assign \vlen_set[30]  = 1'h0;
  assign \vlen_set[31]  = 1'h0;
  assign scalar_wb = mems_rden;
endmodule
