/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module hazard_detect(\id_rs1_addr[0] , \id_rs1_addr[1] , \id_rs1_addr[2] , \id_rs1_addr[3] , \id_rs1_addr[4] , \id_rs2_addr[0] , \id_rs2_addr[1] , \id_rs2_addr[2] , \id_rs2_addr[3] , \id_rs2_addr[4] , \ex_rs1_addr[0] , \ex_rs1_addr[1] , \ex_rs1_addr[2] , \ex_rs1_addr[3] , \ex_rs1_addr[4] , \ex_rs2_addr[0] , \ex_rs2_addr[1] , \ex_rs2_addr[2] , \ex_rs2_addr[3] , \ex_rs2_addr[4] , \ex_rd_addr[0] 
, \ex_rd_addr[1] , \ex_rd_addr[2] , \ex_rd_addr[3] , \ex_rd_addr[4] , ex_mems_rden, \mem_rd_addr[0] , \mem_rd_addr[1] , \mem_rd_addr[2] , \mem_rd_addr[3] , \mem_rd_addr[4] , mem_scalar_wren, \wb_rd_addr[0] , \wb_rd_addr[1] , \wb_rd_addr[2] , \wb_rd_addr[3] , \wb_rd_addr[4] , wb_scalar_wren, \id_vrs1_addr[0] , \id_vrs1_addr[1] , \id_vrs1_addr[2] , \id_vrs1_addr[3] 
, \id_vrs1_addr[4] , \id_vrs2_addr[0] , \id_vrs2_addr[1] , \id_vrs2_addr[2] , \id_vrs2_addr[3] , \id_vrs2_addr[4] , \ex_vrs1_addr[0] , \ex_vrs1_addr[1] , \ex_vrs1_addr[2] , \ex_vrs1_addr[3] , \ex_vrs1_addr[4] , \ex_vrs2_addr[0] , \ex_vrs2_addr[1] , \ex_vrs2_addr[2] , \ex_vrs2_addr[3] , \ex_vrs2_addr[4] , \ex_vrd_addr[0] , \ex_vrd_addr[1] , \ex_vrd_addr[2] , \ex_vrd_addr[3] , \ex_vrd_addr[4] 
, ex_mem_vrden, \mem_vrd_addr[0] , \mem_vrd_addr[1] , \mem_vrd_addr[2] , \mem_vrd_addr[3] , \mem_vrd_addr[4] , mem_vector_wren, \wb_vrd_addr[0] , \wb_vrd_addr[1] , \wb_vrd_addr[2] , \wb_vrd_addr[3] , \wb_vrd_addr[4] , wb_vector_wren, \vrs1_forwarding_sel[0] , \vrs1_forwarding_sel[1] , \vrs2_forwarding_sel[0] , \vrs2_forwarding_sel[1] , \rs1_forwarding_sel[0] , \rs1_forwarding_sel[1] , \rs2_forwarding_sel[0] , \rs2_forwarding_sel[1] 
, vector_stall, scalar_stall);
  input \id_rs1_addr[0] ;
  wire \id_rs1_addr[0] ;
  input \id_rs1_addr[1] ;
  wire \id_rs1_addr[1] ;
  input \id_rs1_addr[2] ;
  wire \id_rs1_addr[2] ;
  input \id_rs1_addr[3] ;
  wire \id_rs1_addr[3] ;
  input \id_rs1_addr[4] ;
  wire \id_rs1_addr[4] ;
  input \id_rs2_addr[0] ;
  wire \id_rs2_addr[0] ;
  input \id_rs2_addr[1] ;
  wire \id_rs2_addr[1] ;
  input \id_rs2_addr[2] ;
  wire \id_rs2_addr[2] ;
  input \id_rs2_addr[3] ;
  wire \id_rs2_addr[3] ;
  input \id_rs2_addr[4] ;
  wire \id_rs2_addr[4] ;
  input \ex_rs1_addr[0] ;
  wire \ex_rs1_addr[0] ;
  input \ex_rs1_addr[1] ;
  wire \ex_rs1_addr[1] ;
  input \ex_rs1_addr[2] ;
  wire \ex_rs1_addr[2] ;
  input \ex_rs1_addr[3] ;
  wire \ex_rs1_addr[3] ;
  input \ex_rs1_addr[4] ;
  wire \ex_rs1_addr[4] ;
  input \ex_rs2_addr[0] ;
  wire \ex_rs2_addr[0] ;
  input \ex_rs2_addr[1] ;
  wire \ex_rs2_addr[1] ;
  input \ex_rs2_addr[2] ;
  wire \ex_rs2_addr[2] ;
  input \ex_rs2_addr[3] ;
  wire \ex_rs2_addr[3] ;
  input \ex_rs2_addr[4] ;
  wire \ex_rs2_addr[4] ;
  input \ex_rd_addr[0] ;
  wire \ex_rd_addr[0] ;
  input \ex_rd_addr[1] ;
  wire \ex_rd_addr[1] ;
  input \ex_rd_addr[2] ;
  wire \ex_rd_addr[2] ;
  input \ex_rd_addr[3] ;
  wire \ex_rd_addr[3] ;
  input \ex_rd_addr[4] ;
  wire \ex_rd_addr[4] ;
  input ex_mems_rden;
  wire ex_mems_rden;
  input \mem_rd_addr[0] ;
  wire \mem_rd_addr[0] ;
  input \mem_rd_addr[1] ;
  wire \mem_rd_addr[1] ;
  input \mem_rd_addr[2] ;
  wire \mem_rd_addr[2] ;
  input \mem_rd_addr[3] ;
  wire \mem_rd_addr[3] ;
  input \mem_rd_addr[4] ;
  wire \mem_rd_addr[4] ;
  input mem_scalar_wren;
  wire mem_scalar_wren;
  input \wb_rd_addr[0] ;
  wire \wb_rd_addr[0] ;
  input \wb_rd_addr[1] ;
  wire \wb_rd_addr[1] ;
  input \wb_rd_addr[2] ;
  wire \wb_rd_addr[2] ;
  input \wb_rd_addr[3] ;
  wire \wb_rd_addr[3] ;
  input \wb_rd_addr[4] ;
  wire \wb_rd_addr[4] ;
  input wb_scalar_wren;
  wire wb_scalar_wren;
  input \id_vrs1_addr[0] ;
  wire \id_vrs1_addr[0] ;
  input \id_vrs1_addr[1] ;
  wire \id_vrs1_addr[1] ;
  input \id_vrs1_addr[2] ;
  wire \id_vrs1_addr[2] ;
  input \id_vrs1_addr[3] ;
  wire \id_vrs1_addr[3] ;
  input \id_vrs1_addr[4] ;
  wire \id_vrs1_addr[4] ;
  input \id_vrs2_addr[0] ;
  wire \id_vrs2_addr[0] ;
  input \id_vrs2_addr[1] ;
  wire \id_vrs2_addr[1] ;
  input \id_vrs2_addr[2] ;
  wire \id_vrs2_addr[2] ;
  input \id_vrs2_addr[3] ;
  wire \id_vrs2_addr[3] ;
  input \id_vrs2_addr[4] ;
  wire \id_vrs2_addr[4] ;
  input \ex_vrs1_addr[0] ;
  wire \ex_vrs1_addr[0] ;
  input \ex_vrs1_addr[1] ;
  wire \ex_vrs1_addr[1] ;
  input \ex_vrs1_addr[2] ;
  wire \ex_vrs1_addr[2] ;
  input \ex_vrs1_addr[3] ;
  wire \ex_vrs1_addr[3] ;
  input \ex_vrs1_addr[4] ;
  wire \ex_vrs1_addr[4] ;
  input \ex_vrs2_addr[0] ;
  wire \ex_vrs2_addr[0] ;
  input \ex_vrs2_addr[1] ;
  wire \ex_vrs2_addr[1] ;
  input \ex_vrs2_addr[2] ;
  wire \ex_vrs2_addr[2] ;
  input \ex_vrs2_addr[3] ;
  wire \ex_vrs2_addr[3] ;
  input \ex_vrs2_addr[4] ;
  wire \ex_vrs2_addr[4] ;
  input \ex_vrd_addr[0] ;
  wire \ex_vrd_addr[0] ;
  input \ex_vrd_addr[1] ;
  wire \ex_vrd_addr[1] ;
  input \ex_vrd_addr[2] ;
  wire \ex_vrd_addr[2] ;
  input \ex_vrd_addr[3] ;
  wire \ex_vrd_addr[3] ;
  input \ex_vrd_addr[4] ;
  wire \ex_vrd_addr[4] ;
  input ex_mem_vrden;
  wire ex_mem_vrden;
  input \mem_vrd_addr[0] ;
  wire \mem_vrd_addr[0] ;
  input \mem_vrd_addr[1] ;
  wire \mem_vrd_addr[1] ;
  input \mem_vrd_addr[2] ;
  wire \mem_vrd_addr[2] ;
  input \mem_vrd_addr[3] ;
  wire \mem_vrd_addr[3] ;
  input \mem_vrd_addr[4] ;
  wire \mem_vrd_addr[4] ;
  input mem_vector_wren;
  wire mem_vector_wren;
  input \wb_vrd_addr[0] ;
  wire \wb_vrd_addr[0] ;
  input \wb_vrd_addr[1] ;
  wire \wb_vrd_addr[1] ;
  input \wb_vrd_addr[2] ;
  wire \wb_vrd_addr[2] ;
  input \wb_vrd_addr[3] ;
  wire \wb_vrd_addr[3] ;
  input \wb_vrd_addr[4] ;
  wire \wb_vrd_addr[4] ;
  input wb_vector_wren;
  wire wb_vector_wren;
  output \vrs1_forwarding_sel[0] ;
  wire \vrs1_forwarding_sel[0] ;
  output \vrs1_forwarding_sel[1] ;
  wire \vrs1_forwarding_sel[1] ;
  output \vrs2_forwarding_sel[0] ;
  wire \vrs2_forwarding_sel[0] ;
  output \vrs2_forwarding_sel[1] ;
  wire \vrs2_forwarding_sel[1] ;
  output \rs1_forwarding_sel[0] ;
  wire \rs1_forwarding_sel[0] ;
  output \rs1_forwarding_sel[1] ;
  wire \rs1_forwarding_sel[1] ;
  output \rs2_forwarding_sel[0] ;
  wire \rs2_forwarding_sel[0] ;
  output \rs2_forwarding_sel[1] ;
  wire \rs2_forwarding_sel[1] ;
  output vector_stall;
  wire vector_stall;
  output scalar_stall;
  wire scalar_stall;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  XOR2_X1 _101_ (
    .A(\ex_vrd_addr[4] ),
    .B(\id_vrs1_addr[4] ),
    .Z(_042_)
  );
  XNOR2_X1 _102_ (
    .A(\ex_vrd_addr[1] ),
    .B(\id_vrs1_addr[1] ),
    .ZN(_043_)
  );
  AOI221_X1 _103_ (
    .A(_042_),
    .B1(\id_vrs1_addr[0] ),
    .B2(_090_),
    .C1(_088_),
    .C2(\id_vrs1_addr[3] ),
    .ZN(_044_)
  );
  XOR2_X1 _104_ (
    .A(\ex_vrd_addr[2] ),
    .B(\id_vrs1_addr[2] ),
    .Z(_045_)
  );
  AOI221_X1 _105_ (
    .A(_045_),
    .B1(_092_),
    .B2(\ex_vrd_addr[0] ),
    .C1(\ex_vrd_addr[3] ),
    .C2(_093_),
    .ZN(_046_)
  );
  NAND3_X1 _106_ (
    .A1(_043_),
    .A2(_044_),
    .A3(_046_),
    .ZN(_047_)
  );
  XNOR2_X1 _107_ (
    .A(\ex_vrd_addr[2] ),
    .B(\id_vrs2_addr[2] ),
    .ZN(_048_)
  );
  XOR2_X1 _108_ (
    .A(\ex_vrd_addr[4] ),
    .B(\id_vrs2_addr[4] ),
    .Z(_049_)
  );
  XOR2_X1 _109_ (
    .A(\ex_vrd_addr[1] ),
    .B(\id_vrs2_addr[1] ),
    .Z(_050_)
  );
  AOI221_X1 _110_ (
    .A(_050_),
    .B1(_091_),
    .B2(\ex_vrd_addr[0] ),
    .C1(_088_),
    .C2(\id_vrs2_addr[3] ),
    .ZN(_051_)
  );
  AOI221_X1 _111_ (
    .A(_049_),
    .B1(\id_vrs2_addr[0] ),
    .B2(_090_),
    .C1(\ex_vrd_addr[3] ),
    .C2(_089_),
    .ZN(_052_)
  );
  NAND3_X1 _112_ (
    .A1(_048_),
    .A2(_051_),
    .A3(_052_),
    .ZN(_053_)
  );
  NOR4_X1 _113_ (
    .A1(\ex_vrd_addr[3] ),
    .A2(\ex_vrd_addr[1] ),
    .A3(\ex_vrd_addr[4] ),
    .A4(\ex_vrd_addr[2] ),
    .ZN(_054_)
  );
  AOI221_X1 _114_ (
    .A(_094_),
    .B1(_047_),
    .B2(_053_),
    .C1(_054_),
    .C2(_090_),
    .ZN(vector_stall)
  );
  XNOR2_X1 _115_ (
    .A(\ex_rd_addr[2] ),
    .B(\id_rs1_addr[2] ),
    .ZN(_055_)
  );
  XOR2_X1 _116_ (
    .A(\ex_rd_addr[1] ),
    .B(\id_rs1_addr[1] ),
    .Z(_056_)
  );
  XOR2_X1 _117_ (
    .A(\ex_rd_addr[4] ),
    .B(\id_rs1_addr[4] ),
    .Z(_057_)
  );
  AOI221_X1 _118_ (
    .A(_057_),
    .B1(\id_rs1_addr[0] ),
    .B2(_099_),
    .C1(_097_),
    .C2(\id_rs1_addr[3] ),
    .ZN(_058_)
  );
  AOI221_X1 _119_ (
    .A(_056_),
    .B1(_100_),
    .B2(\ex_rd_addr[0] ),
    .C1(\ex_rd_addr[3] ),
    .C2(_000_),
    .ZN(_059_)
  );
  NAND3_X1 _120_ (
    .A1(_055_),
    .A2(_058_),
    .A3(_059_),
    .ZN(_060_)
  );
  XOR2_X1 _121_ (
    .A(\ex_rd_addr[2] ),
    .B(\id_rs2_addr[2] ),
    .Z(_061_)
  );
  XOR2_X1 _122_ (
    .A(\ex_rd_addr[0] ),
    .B(\id_rs2_addr[0] ),
    .Z(_062_)
  );
  AOI221_X1 _123_ (
    .A(_061_),
    .B1(_098_),
    .B2(\ex_rd_addr[3] ),
    .C1(_095_),
    .C2(\id_rs2_addr[4] ),
    .ZN(_063_)
  );
  AOI221_X1 _124_ (
    .A(_062_),
    .B1(\id_rs2_addr[3] ),
    .B2(_097_),
    .C1(\ex_rd_addr[4] ),
    .C2(_096_),
    .ZN(_064_)
  );
  XNOR2_X1 _125_ (
    .A(\ex_rd_addr[1] ),
    .B(\id_rs2_addr[1] ),
    .ZN(_065_)
  );
  NAND3_X1 _126_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_065_),
    .ZN(_066_)
  );
  NOR4_X1 _127_ (
    .A1(\ex_rd_addr[4] ),
    .A2(\ex_rd_addr[1] ),
    .A3(\ex_rd_addr[0] ),
    .A4(\ex_rd_addr[2] ),
    .ZN(_067_)
  );
  AOI221_X1 _128_ (
    .A(_001_),
    .B1(_060_),
    .B2(_066_),
    .C1(_067_),
    .C2(_097_),
    .ZN(scalar_stall)
  );
  XOR2_X1 _129_ (
    .A(\mem_rd_addr[0] ),
    .B(\ex_rs2_addr[0] ),
    .Z(_068_)
  );
  XOR2_X1 _130_ (
    .A(\mem_rd_addr[3] ),
    .B(\ex_rs2_addr[3] ),
    .Z(_069_)
  );
  XNOR2_X1 _131_ (
    .A(\mem_rd_addr[2] ),
    .B(\ex_rs2_addr[2] ),
    .ZN(_070_)
  );
  XNOR2_X1 _132_ (
    .A(\mem_rd_addr[1] ),
    .B(\ex_rs2_addr[1] ),
    .ZN(_071_)
  );
  XNOR2_X1 _133_ (
    .A(\mem_rd_addr[4] ),
    .B(\ex_rs2_addr[4] ),
    .ZN(_072_)
  );
  NAND3_X1 _134_ (
    .A1(_070_),
    .A2(_071_),
    .A3(_072_),
    .ZN(_073_)
  );
  NOR4_X1 _135_ (
    .A1(_020_),
    .A2(_068_),
    .A3(_069_),
    .A4(_073_),
    .ZN(\rs2_forwarding_sel[1] )
  );
  XNOR2_X1 _136_ (
    .A(\wb_vrd_addr[4] ),
    .B(\ex_vrs1_addr[4] ),
    .ZN(_074_)
  );
  XNOR2_X1 _137_ (
    .A(\wb_vrd_addr[0] ),
    .B(\ex_vrs1_addr[0] ),
    .ZN(_075_)
  );
  XOR2_X1 _138_ (
    .A(\wb_vrd_addr[1] ),
    .B(\ex_vrs1_addr[1] ),
    .Z(_076_)
  );
  XOR2_X1 _139_ (
    .A(\wb_vrd_addr[3] ),
    .B(\ex_vrs1_addr[3] ),
    .Z(_077_)
  );
  XOR2_X1 _140_ (
    .A(\wb_vrd_addr[2] ),
    .B(\ex_vrs1_addr[2] ),
    .Z(_078_)
  );
  NOR3_X1 _141_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_078_),
    .ZN(_079_)
  );
  NAND3_X1 _142_ (
    .A1(_074_),
    .A2(_075_),
    .A3(_079_),
    .ZN(_080_)
  );
  NOR3_X1 _143_ (
    .A1(_011_),
    .A2(\vrs1_forwarding_sel[1] ),
    .A3(_080_),
    .ZN(\vrs1_forwarding_sel[0] )
  );
  XOR2_X1 _144_ (
    .A(\wb_rd_addr[1] ),
    .B(\ex_rs2_addr[1] ),
    .Z(_081_)
  );
  XOR2_X1 _145_ (
    .A(\wb_rd_addr[0] ),
    .B(\ex_rs2_addr[0] ),
    .Z(_082_)
  );
  XNOR2_X1 _146_ (
    .A(\wb_rd_addr[2] ),
    .B(\ex_rs2_addr[2] ),
    .ZN(_083_)
  );
  XNOR2_X1 _147_ (
    .A(\wb_rd_addr[3] ),
    .B(\ex_rs2_addr[3] ),
    .ZN(_084_)
  );
  XOR2_X1 _148_ (
    .A(\wb_rd_addr[4] ),
    .B(\ex_rs2_addr[4] ),
    .Z(_085_)
  );
  NOR3_X1 _149_ (
    .A1(_081_),
    .A2(_082_),
    .A3(_085_),
    .ZN(_086_)
  );
  NAND3_X1 _150_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_086_),
    .ZN(_087_)
  );
  NOR3_X1 _151_ (
    .A1(_028_),
    .A2(\rs2_forwarding_sel[1] ),
    .A3(_087_),
    .ZN(\rs2_forwarding_sel[0] )
  );
  INV_X1 _152_ (
    .A(\ex_vrd_addr[3] ),
    .ZN(_088_)
  );
  INV_X1 _153_ (
    .A(\id_vrs2_addr[3] ),
    .ZN(_089_)
  );
  INV_X1 _154_ (
    .A(\ex_vrd_addr[0] ),
    .ZN(_090_)
  );
  INV_X1 _155_ (
    .A(\id_vrs2_addr[0] ),
    .ZN(_091_)
  );
  INV_X1 _156_ (
    .A(\id_vrs1_addr[0] ),
    .ZN(_092_)
  );
  INV_X1 _157_ (
    .A(\id_vrs1_addr[3] ),
    .ZN(_093_)
  );
  INV_X1 _158_ (
    .A(ex_mem_vrden),
    .ZN(_094_)
  );
  INV_X1 _159_ (
    .A(\ex_rd_addr[4] ),
    .ZN(_095_)
  );
  INV_X1 _160_ (
    .A(\id_rs2_addr[4] ),
    .ZN(_096_)
  );
  INV_X1 _161_ (
    .A(\ex_rd_addr[3] ),
    .ZN(_097_)
  );
  INV_X1 _162_ (
    .A(\id_rs2_addr[3] ),
    .ZN(_098_)
  );
  INV_X1 _163_ (
    .A(\ex_rd_addr[0] ),
    .ZN(_099_)
  );
  INV_X1 _164_ (
    .A(\id_rs1_addr[0] ),
    .ZN(_100_)
  );
  INV_X1 _165_ (
    .A(\id_rs1_addr[3] ),
    .ZN(_000_)
  );
  INV_X1 _166_ (
    .A(ex_mems_rden),
    .ZN(_001_)
  );
  OR4_X1 _167_ (
    .A1(\mem_vrd_addr[3] ),
    .A2(\mem_vrd_addr[2] ),
    .A3(\mem_vrd_addr[1] ),
    .A4(\mem_vrd_addr[0] ),
    .ZN(_002_)
  );
  OAI21_X1 _168_ (
    .A(mem_vector_wren),
    .B1(_002_),
    .B2(\mem_vrd_addr[4] ),
    .ZN(_003_)
  );
  XOR2_X1 _169_ (
    .A(\mem_vrd_addr[3] ),
    .B(\ex_vrs2_addr[3] ),
    .Z(_004_)
  );
  XOR2_X1 _170_ (
    .A(\mem_vrd_addr[1] ),
    .B(\ex_vrs2_addr[1] ),
    .Z(_005_)
  );
  XNOR2_X1 _171_ (
    .A(\mem_vrd_addr[0] ),
    .B(\ex_vrs2_addr[0] ),
    .ZN(_006_)
  );
  XNOR2_X1 _172_ (
    .A(\mem_vrd_addr[2] ),
    .B(\ex_vrs2_addr[2] ),
    .ZN(_007_)
  );
  XNOR2_X1 _173_ (
    .A(\mem_vrd_addr[4] ),
    .B(\ex_vrs2_addr[4] ),
    .ZN(_008_)
  );
  NAND3_X1 _174_ (
    .A1(_006_),
    .A2(_007_),
    .A3(_008_),
    .ZN(_009_)
  );
  NOR4_X1 _175_ (
    .A1(_003_),
    .A2(_004_),
    .A3(_005_),
    .A4(_009_),
    .ZN(\vrs2_forwarding_sel[1] )
  );
  OR4_X1 _176_ (
    .A1(\wb_vrd_addr[3] ),
    .A2(\wb_vrd_addr[2] ),
    .A3(\wb_vrd_addr[1] ),
    .A4(\wb_vrd_addr[0] ),
    .ZN(_010_)
  );
  OAI21_X1 _177_ (
    .A(wb_vector_wren),
    .B1(_010_),
    .B2(\wb_vrd_addr[4] ),
    .ZN(_011_)
  );
  XNOR2_X1 _178_ (
    .A(\ex_vrs2_addr[2] ),
    .B(\wb_vrd_addr[2] ),
    .ZN(_012_)
  );
  XNOR2_X1 _179_ (
    .A(\ex_vrs2_addr[1] ),
    .B(\wb_vrd_addr[1] ),
    .ZN(_013_)
  );
  XOR2_X1 _180_ (
    .A(\ex_vrs2_addr[4] ),
    .B(\wb_vrd_addr[4] ),
    .Z(_014_)
  );
  XOR2_X1 _181_ (
    .A(\ex_vrs2_addr[3] ),
    .B(\wb_vrd_addr[3] ),
    .Z(_015_)
  );
  XOR2_X1 _182_ (
    .A(\ex_vrs2_addr[0] ),
    .B(\wb_vrd_addr[0] ),
    .Z(_016_)
  );
  NOR3_X1 _183_ (
    .A1(_014_),
    .A2(_015_),
    .A3(_016_),
    .ZN(_017_)
  );
  NAND3_X1 _184_ (
    .A1(_012_),
    .A2(_013_),
    .A3(_017_),
    .ZN(_018_)
  );
  NOR3_X1 _185_ (
    .A1(\vrs2_forwarding_sel[1] ),
    .A2(_011_),
    .A3(_018_),
    .ZN(\vrs2_forwarding_sel[0] )
  );
  OR4_X1 _186_ (
    .A1(\mem_rd_addr[3] ),
    .A2(\mem_rd_addr[2] ),
    .A3(\mem_rd_addr[1] ),
    .A4(\mem_rd_addr[0] ),
    .ZN(_019_)
  );
  OAI21_X1 _187_ (
    .A(mem_scalar_wren),
    .B1(_019_),
    .B2(\mem_rd_addr[4] ),
    .ZN(_020_)
  );
  XOR2_X1 _188_ (
    .A(\mem_rd_addr[2] ),
    .B(\ex_rs1_addr[2] ),
    .Z(_021_)
  );
  XOR2_X1 _189_ (
    .A(\mem_rd_addr[4] ),
    .B(\ex_rs1_addr[4] ),
    .Z(_022_)
  );
  XNOR2_X1 _190_ (
    .A(\mem_rd_addr[3] ),
    .B(\ex_rs1_addr[3] ),
    .ZN(_023_)
  );
  XNOR2_X1 _191_ (
    .A(\mem_rd_addr[0] ),
    .B(\ex_rs1_addr[0] ),
    .ZN(_024_)
  );
  XNOR2_X1 _192_ (
    .A(\mem_rd_addr[1] ),
    .B(\ex_rs1_addr[1] ),
    .ZN(_025_)
  );
  NAND3_X1 _193_ (
    .A1(_023_),
    .A2(_024_),
    .A3(_025_),
    .ZN(_026_)
  );
  NOR4_X1 _194_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_022_),
    .A4(_026_),
    .ZN(\rs1_forwarding_sel[1] )
  );
  OR4_X1 _195_ (
    .A1(\wb_rd_addr[3] ),
    .A2(\wb_rd_addr[2] ),
    .A3(\wb_rd_addr[1] ),
    .A4(\wb_rd_addr[0] ),
    .ZN(_027_)
  );
  OAI21_X1 _196_ (
    .A(wb_scalar_wren),
    .B1(_027_),
    .B2(\wb_rd_addr[4] ),
    .ZN(_028_)
  );
  XNOR2_X1 _197_ (
    .A(\ex_rs1_addr[2] ),
    .B(\wb_rd_addr[2] ),
    .ZN(_029_)
  );
  XNOR2_X1 _198_ (
    .A(\ex_rs1_addr[1] ),
    .B(\wb_rd_addr[1] ),
    .ZN(_030_)
  );
  XOR2_X1 _199_ (
    .A(\ex_rs1_addr[4] ),
    .B(\wb_rd_addr[4] ),
    .Z(_031_)
  );
  XOR2_X1 _200_ (
    .A(\ex_rs1_addr[0] ),
    .B(\wb_rd_addr[0] ),
    .Z(_032_)
  );
  XOR2_X1 _201_ (
    .A(\ex_rs1_addr[3] ),
    .B(\wb_rd_addr[3] ),
    .Z(_033_)
  );
  NOR3_X1 _202_ (
    .A1(_031_),
    .A2(_032_),
    .A3(_033_),
    .ZN(_034_)
  );
  NAND3_X1 _203_ (
    .A1(_029_),
    .A2(_030_),
    .A3(_034_),
    .ZN(_035_)
  );
  NOR3_X1 _204_ (
    .A1(\rs1_forwarding_sel[1] ),
    .A2(_028_),
    .A3(_035_),
    .ZN(\rs1_forwarding_sel[0] )
  );
  XOR2_X1 _205_ (
    .A(\mem_vrd_addr[1] ),
    .B(\ex_vrs1_addr[1] ),
    .Z(_036_)
  );
  XOR2_X1 _206_ (
    .A(\mem_vrd_addr[2] ),
    .B(\ex_vrs1_addr[2] ),
    .Z(_037_)
  );
  XNOR2_X1 _207_ (
    .A(\mem_vrd_addr[0] ),
    .B(\ex_vrs1_addr[0] ),
    .ZN(_038_)
  );
  XNOR2_X1 _208_ (
    .A(\mem_vrd_addr[4] ),
    .B(\ex_vrs1_addr[4] ),
    .ZN(_039_)
  );
  XNOR2_X1 _209_ (
    .A(\mem_vrd_addr[3] ),
    .B(\ex_vrs1_addr[3] ),
    .ZN(_040_)
  );
  NAND3_X1 _210_ (
    .A1(_038_),
    .A2(_039_),
    .A3(_040_),
    .ZN(_041_)
  );
  NOR4_X1 _211_ (
    .A1(_003_),
    .A2(_036_),
    .A3(_037_),
    .A4(_041_),
    .ZN(\vrs1_forwarding_sel[1] )
  );
endmodule
