/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module immgen(\inst_i[0] , \inst_i[1] , \inst_i[2] , \inst_i[3] , \inst_i[4] , \inst_i[5] , \inst_i[6] , \inst_i[7] , \inst_i[8] , \inst_i[9] , \inst_i[10] , \inst_i[11] , \inst_i[12] , \inst_i[13] , \inst_i[14] , \inst_i[15] , \inst_i[16] , \inst_i[17] , \inst_i[18] , \inst_i[19] , \inst_i[20] 
, \inst_i[21] , \inst_i[22] , \inst_i[23] , \inst_i[24] , \inst_i[25] , \inst_i[26] , \inst_i[27] , \inst_i[28] , \inst_i[29] , \inst_i[30] , \inst_i[31] , \imm_o[0] , \imm_o[1] , \imm_o[2] , \imm_o[3] , \imm_o[4] , \imm_o[5] , \imm_o[6] , \imm_o[7] , \imm_o[8] , \imm_o[9] 
, \imm_o[10] , \imm_o[11] , \imm_o[12] , \imm_o[13] , \imm_o[14] , \imm_o[15] , \imm_o[16] , \imm_o[17] , \imm_o[18] , \imm_o[19] , \imm_o[20] , \imm_o[21] , \imm_o[22] , \imm_o[23] , \imm_o[24] , \imm_o[25] , \imm_o[26] , \imm_o[27] , \imm_o[28] , \imm_o[29] , \imm_o[30] 
, \imm_o[31] );
  input \inst_i[0] ;
  wire \inst_i[0] ;
  input \inst_i[1] ;
  wire \inst_i[1] ;
  input \inst_i[2] ;
  wire \inst_i[2] ;
  input \inst_i[3] ;
  wire \inst_i[3] ;
  input \inst_i[4] ;
  wire \inst_i[4] ;
  input \inst_i[5] ;
  wire \inst_i[5] ;
  input \inst_i[6] ;
  wire \inst_i[6] ;
  input \inst_i[7] ;
  wire \inst_i[7] ;
  input \inst_i[8] ;
  wire \inst_i[8] ;
  input \inst_i[9] ;
  wire \inst_i[9] ;
  input \inst_i[10] ;
  wire \inst_i[10] ;
  input \inst_i[11] ;
  wire \inst_i[11] ;
  input \inst_i[12] ;
  wire \inst_i[12] ;
  input \inst_i[13] ;
  wire \inst_i[13] ;
  input \inst_i[14] ;
  wire \inst_i[14] ;
  input \inst_i[15] ;
  wire \inst_i[15] ;
  input \inst_i[16] ;
  wire \inst_i[16] ;
  input \inst_i[17] ;
  wire \inst_i[17] ;
  input \inst_i[18] ;
  wire \inst_i[18] ;
  input \inst_i[19] ;
  wire \inst_i[19] ;
  input \inst_i[20] ;
  wire \inst_i[20] ;
  input \inst_i[21] ;
  wire \inst_i[21] ;
  input \inst_i[22] ;
  wire \inst_i[22] ;
  input \inst_i[23] ;
  wire \inst_i[23] ;
  input \inst_i[24] ;
  wire \inst_i[24] ;
  input \inst_i[25] ;
  wire \inst_i[25] ;
  input \inst_i[26] ;
  wire \inst_i[26] ;
  input \inst_i[27] ;
  wire \inst_i[27] ;
  input \inst_i[28] ;
  wire \inst_i[28] ;
  input \inst_i[29] ;
  wire \inst_i[29] ;
  input \inst_i[30] ;
  wire \inst_i[30] ;
  input \inst_i[31] ;
  wire \inst_i[31] ;
  output \imm_o[0] ;
  wire \imm_o[0] ;
  output \imm_o[1] ;
  wire \imm_o[1] ;
  output \imm_o[2] ;
  wire \imm_o[2] ;
  output \imm_o[3] ;
  wire \imm_o[3] ;
  output \imm_o[4] ;
  wire \imm_o[4] ;
  output \imm_o[5] ;
  wire \imm_o[5] ;
  output \imm_o[6] ;
  wire \imm_o[6] ;
  output \imm_o[7] ;
  wire \imm_o[7] ;
  output \imm_o[8] ;
  wire \imm_o[8] ;
  output \imm_o[9] ;
  wire \imm_o[9] ;
  output \imm_o[10] ;
  wire \imm_o[10] ;
  output \imm_o[11] ;
  wire \imm_o[11] ;
  output \imm_o[12] ;
  wire \imm_o[12] ;
  output \imm_o[13] ;
  wire \imm_o[13] ;
  output \imm_o[14] ;
  wire \imm_o[14] ;
  output \imm_o[15] ;
  wire \imm_o[15] ;
  output \imm_o[16] ;
  wire \imm_o[16] ;
  output \imm_o[17] ;
  wire \imm_o[17] ;
  output \imm_o[18] ;
  wire \imm_o[18] ;
  output \imm_o[19] ;
  wire \imm_o[19] ;
  output \imm_o[20] ;
  wire \imm_o[20] ;
  output \imm_o[21] ;
  wire \imm_o[21] ;
  output \imm_o[22] ;
  wire \imm_o[22] ;
  output \imm_o[23] ;
  wire \imm_o[23] ;
  output \imm_o[24] ;
  wire \imm_o[24] ;
  output \imm_o[25] ;
  wire \imm_o[25] ;
  output \imm_o[26] ;
  wire \imm_o[26] ;
  output \imm_o[27] ;
  wire \imm_o[27] ;
  output \imm_o[28] ;
  wire \imm_o[28] ;
  output \imm_o[29] ;
  wire \imm_o[29] ;
  output \imm_o[30] ;
  wire \imm_o[30] ;
  output \imm_o[31] ;
  wire \imm_o[31] ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  INV_X1 _056_ (
    .A(\inst_i[3] ),
    .ZN(_022_)
  );
  INV_X1 _057_ (
    .A(\inst_i[5] ),
    .ZN(_023_)
  );
  INV_X1 _058_ (
    .A(\inst_i[4] ),
    .ZN(_024_)
  );
  INV_X1 _059_ (
    .A(\inst_i[6] ),
    .ZN(_025_)
  );
  INV_X1 _060_ (
    .A(\inst_i[31] ),
    .ZN(_026_)
  );
  INV_X1 _061_ (
    .A(\inst_i[14] ),
    .ZN(_027_)
  );
  INV_X1 _062_ (
    .A(\inst_i[13] ),
    .ZN(_028_)
  );
  INV_X1 _063_ (
    .A(\inst_i[12] ),
    .ZN(_029_)
  );
  INV_X1 _064_ (
    .A(\inst_i[18] ),
    .ZN(_030_)
  );
  INV_X1 _065_ (
    .A(\inst_i[17] ),
    .ZN(_031_)
  );
  INV_X1 _066_ (
    .A(\inst_i[16] ),
    .ZN(_032_)
  );
  INV_X1 _067_ (
    .A(\inst_i[15] ),
    .ZN(_033_)
  );
  INV_X1 _068_ (
    .A(\inst_i[19] ),
    .ZN(_034_)
  );
  AND2_X1 _069_ (
    .A1(\inst_i[1] ),
    .A2(\inst_i[0] ),
    .ZN(_035_)
  );
  NAND2_X1 _070_ (
    .A1(\inst_i[2] ),
    .A2(_035_),
    .ZN(_036_)
  );
  NAND2_X1 _071_ (
    .A1(\inst_i[4] ),
    .A2(_025_),
    .ZN(_037_)
  );
  NOR3_X1 _072_ (
    .A1(\inst_i[3] ),
    .A2(_036_),
    .A3(_037_),
    .ZN(_038_)
  );
  NAND2_X1 _073_ (
    .A1(\inst_i[28] ),
    .A2(_038_),
    .ZN(_039_)
  );
  NAND2_X1 _074_ (
    .A1(\inst_i[5] ),
    .A2(_024_),
    .ZN(_040_)
  );
  NOR2_X1 _075_ (
    .A1(\inst_i[2] ),
    .A2(\inst_i[3] ),
    .ZN(_041_)
  );
  NAND2_X1 _076_ (
    .A1(_035_),
    .A2(_041_),
    .ZN(_042_)
  );
  NOR2_X1 _077_ (
    .A1(_040_),
    .A2(_042_),
    .ZN(_043_)
  );
  AOI21_X1 _078_ (
    .A(_029_),
    .B1(\inst_i[13] ),
    .B2(\inst_i[14] ),
    .ZN(_044_)
  );
  NOR4_X1 _079_ (
    .A1(\inst_i[5] ),
    .A2(_026_),
    .A3(_037_),
    .A4(_042_),
    .ZN(_045_)
  );
  NAND4_X1 _080_ (
    .A1(_023_),
    .A2(\inst_i[31] ),
    .A3(_035_),
    .A4(_041_),
    .ZN(_046_)
  );
  OAI33_X1 _081_ (
    .A1(_026_),
    .A2(_040_),
    .A3(_042_),
    .B1(_044_),
    .B2(_046_),
    .B3(_037_),
    .ZN(_047_)
  );
  NAND3_X1 _082_ (
    .A1(\inst_i[5] ),
    .A2(_024_),
    .A3(\inst_i[6] ),
    .ZN(_048_)
  );
  NAND4_X1 _083_ (
    .A1(_023_),
    .A2(_025_),
    .A3(_035_),
    .A4(_041_),
    .ZN(_049_)
  );
  OAI33_X1 _084_ (
    .A1(\inst_i[5] ),
    .A2(\inst_i[6] ),
    .A3(_042_),
    .B1(_048_),
    .B2(_036_),
    .B3(\inst_i[3] ),
    .ZN(_050_)
  );
  NOR2_X1 _085_ (
    .A1(\inst_i[4] ),
    .A2(_026_),
    .ZN(_051_)
  );
  NAND2_X1 _086_ (
    .A1(_050_),
    .A2(_051_),
    .ZN(_052_)
  );
  AOI21_X1 _087_ (
    .A(_047_),
    .B1(_050_),
    .B2(_051_),
    .ZN(_053_)
  );
  NOR3_X1 _088_ (
    .A1(_022_),
    .A2(_036_),
    .A3(_048_),
    .ZN(_054_)
  );
  AOI221_X1 _089_ (
    .A(_047_),
    .B1(_050_),
    .B2(_051_),
    .C1(_054_),
    .C2(\inst_i[31] ),
    .ZN(_055_)
  );
  NAND2_X1 _090_ (
    .A1(_039_),
    .A2(_055_),
    .ZN(\imm_o[28] )
  );
  NOR2_X1 _091_ (
    .A1(_038_),
    .A2(_054_),
    .ZN(_000_)
  );
  OAI21_X1 _092_ (
    .A(_053_),
    .B1(_000_),
    .B2(_030_),
    .ZN(\imm_o[18] )
  );
  OAI21_X1 _093_ (
    .A(_053_),
    .B1(_000_),
    .B2(_031_),
    .ZN(\imm_o[17] )
  );
  NAND2_X1 _094_ (
    .A1(\inst_i[22] ),
    .A2(_038_),
    .ZN(_001_)
  );
  NAND2_X1 _095_ (
    .A1(_055_),
    .A2(_001_),
    .ZN(\imm_o[22] )
  );
  OAI21_X1 _096_ (
    .A(_053_),
    .B1(_000_),
    .B2(_032_),
    .ZN(\imm_o[16] )
  );
  NAND2_X1 _097_ (
    .A1(\inst_i[27] ),
    .A2(_038_),
    .ZN(_002_)
  );
  NAND2_X1 _098_ (
    .A1(_055_),
    .A2(_002_),
    .ZN(\imm_o[27] )
  );
  OAI21_X1 _099_ (
    .A(_053_),
    .B1(_000_),
    .B2(_033_),
    .ZN(\imm_o[15] )
  );
  OAI21_X1 _100_ (
    .A(_053_),
    .B1(_000_),
    .B2(_027_),
    .ZN(\imm_o[14] )
  );
  NAND2_X1 _101_ (
    .A1(\inst_i[29] ),
    .A2(_038_),
    .ZN(_003_)
  );
  NAND2_X1 _102_ (
    .A1(_055_),
    .A2(_003_),
    .ZN(\imm_o[29] )
  );
  OAI21_X1 _103_ (
    .A(_053_),
    .B1(_000_),
    .B2(_028_),
    .ZN(\imm_o[13] )
  );
  NAND2_X1 _104_ (
    .A1(\inst_i[21] ),
    .A2(_038_),
    .ZN(_004_)
  );
  NAND2_X1 _105_ (
    .A1(_055_),
    .A2(_004_),
    .ZN(\imm_o[21] )
  );
  NAND2_X1 _106_ (
    .A1(\inst_i[26] ),
    .A2(_038_),
    .ZN(_005_)
  );
  NAND2_X1 _107_ (
    .A1(_055_),
    .A2(_005_),
    .ZN(\imm_o[26] )
  );
  OAI21_X1 _108_ (
    .A(_053_),
    .B1(_000_),
    .B2(_029_),
    .ZN(\imm_o[12] )
  );
  NAND2_X1 _109_ (
    .A1(\inst_i[23] ),
    .A2(_038_),
    .ZN(_006_)
  );
  NAND2_X1 _110_ (
    .A1(_055_),
    .A2(_006_),
    .ZN(\imm_o[23] )
  );
  NAND3_X1 _111_ (
    .A1(_025_),
    .A2(\inst_i[31] ),
    .A3(_043_),
    .ZN(_007_)
  );
  NOR2_X1 _112_ (
    .A1(_042_),
    .A2(_048_),
    .ZN(_008_)
  );
  AOI221_X1 _113_ (
    .A(_045_),
    .B1(_054_),
    .B2(\inst_i[20] ),
    .C1(_008_),
    .C2(\inst_i[7] ),
    .ZN(_009_)
  );
  NAND3_X1 _114_ (
    .A1(_052_),
    .A2(_007_),
    .A3(_009_),
    .ZN(\imm_o[11] )
  );
  OAI21_X1 _115_ (
    .A(_049_),
    .B1(_048_),
    .B2(_036_),
    .ZN(_010_)
  );
  OR2_X1 _116_ (
    .A1(_043_),
    .A2(_010_),
    .ZN(_011_)
  );
  AND2_X1 _117_ (
    .A1(\inst_i[30] ),
    .A2(_011_),
    .ZN(\imm_o[10] )
  );
  AND2_X1 _118_ (
    .A1(\inst_i[29] ),
    .A2(_011_),
    .ZN(\imm_o[9] )
  );
  AND2_X1 _119_ (
    .A1(\inst_i[28] ),
    .A2(_011_),
    .ZN(\imm_o[8] )
  );
  AND2_X1 _120_ (
    .A1(\inst_i[27] ),
    .A2(_011_),
    .ZN(\imm_o[7] )
  );
  AND2_X1 _121_ (
    .A1(\inst_i[26] ),
    .A2(_011_),
    .ZN(\imm_o[6] )
  );
  NAND2_X1 _122_ (
    .A1(\inst_i[25] ),
    .A2(_038_),
    .ZN(_012_)
  );
  NAND2_X1 _123_ (
    .A1(_055_),
    .A2(_012_),
    .ZN(\imm_o[25] )
  );
  AND2_X1 _124_ (
    .A1(\inst_i[25] ),
    .A2(_011_),
    .ZN(\imm_o[5] )
  );
  AOI22_X1 _125_ (
    .A1(\inst_i[11] ),
    .A2(_043_),
    .B1(_010_),
    .B2(\inst_i[24] ),
    .ZN(_013_)
  );
  INV_X1 _126_ (
    .A(_013_),
    .ZN(\imm_o[4] )
  );
  NAND2_X1 _127_ (
    .A1(\inst_i[20] ),
    .A2(_038_),
    .ZN(_014_)
  );
  NAND2_X1 _128_ (
    .A1(_055_),
    .A2(_014_),
    .ZN(\imm_o[20] )
  );
  AOI22_X1 _129_ (
    .A1(\inst_i[10] ),
    .A2(_043_),
    .B1(_010_),
    .B2(\inst_i[23] ),
    .ZN(_015_)
  );
  INV_X1 _130_ (
    .A(_015_),
    .ZN(\imm_o[3] )
  );
  OAI21_X1 _131_ (
    .A(_053_),
    .B1(_000_),
    .B2(_034_),
    .ZN(\imm_o[19] )
  );
  AOI22_X1 _132_ (
    .A1(\inst_i[9] ),
    .A2(_043_),
    .B1(_010_),
    .B2(\inst_i[22] ),
    .ZN(_016_)
  );
  INV_X1 _133_ (
    .A(_016_),
    .ZN(\imm_o[2] )
  );
  AOI22_X1 _134_ (
    .A1(\inst_i[8] ),
    .A2(_043_),
    .B1(_010_),
    .B2(\inst_i[21] ),
    .ZN(_017_)
  );
  INV_X1 _135_ (
    .A(_017_),
    .ZN(\imm_o[1] )
  );
  NAND2_X1 _136_ (
    .A1(\inst_i[20] ),
    .A2(_050_),
    .ZN(_018_)
  );
  NAND3_X1 _137_ (
    .A1(_025_),
    .A2(\inst_i[7] ),
    .A3(_043_),
    .ZN(_019_)
  );
  NAND2_X1 _138_ (
    .A1(_018_),
    .A2(_019_),
    .ZN(\imm_o[0] )
  );
  NAND2_X1 _139_ (
    .A1(\inst_i[30] ),
    .A2(_038_),
    .ZN(_020_)
  );
  NAND2_X1 _140_ (
    .A1(_055_),
    .A2(_020_),
    .ZN(\imm_o[30] )
  );
  NAND2_X1 _141_ (
    .A1(\inst_i[24] ),
    .A2(_038_),
    .ZN(_021_)
  );
  NAND2_X1 _142_ (
    .A1(_055_),
    .A2(_021_),
    .ZN(\imm_o[24] )
  );
  OAI21_X1 _143_ (
    .A(_053_),
    .B1(_000_),
    .B2(_026_),
    .ZN(\imm_o[31] )
  );
endmodule
