/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module vector_immgen(\inst_i[0] , \inst_i[1] , \inst_i[2] , \inst_i[3] , \inst_i[4] , \inst_i[5] , \inst_i[6] , \inst_i[7] , \inst_i[8] , \inst_i[9] , \inst_i[10] , \inst_i[11] , \inst_i[12] , \inst_i[13] , \inst_i[14] , \inst_i[15] , \inst_i[16] , \inst_i[17] , \inst_i[18] , \inst_i[19] , \inst_i[20] 
, \inst_i[21] , \inst_i[22] , \inst_i[23] , \inst_i[24] , \inst_i[25] , \inst_i[26] , \inst_i[27] , \inst_i[28] , \inst_i[29] , \inst_i[30] , \inst_i[31] , \vimm_o[0] , \vimm_o[1] , \vimm_o[2] , \vimm_o[3] , \vimm_o[4] , \vimm_o[5] , \vimm_o[6] , \vimm_o[7] , \vimm_o[8] , \vimm_o[9] 
, \vimm_o[10] , \vimm_o[11] , \vimm_o[12] , \vimm_o[13] , \vimm_o[14] , \vimm_o[15] , \vimm_o[16] , \vimm_o[17] , \vimm_o[18] , \vimm_o[19] , \vimm_o[20] , \vimm_o[21] , \vimm_o[22] , \vimm_o[23] , \vimm_o[24] , \vimm_o[25] , \vimm_o[26] , \vimm_o[27] , \vimm_o[28] , \vimm_o[29] , \vimm_o[30] 
, \vimm_o[31] , \vimm_o[32] , \vimm_o[33] , \vimm_o[34] , \vimm_o[35] , \vimm_o[36] , \vimm_o[37] , \vimm_o[38] , \vimm_o[39] , \vimm_o[40] , \vimm_o[41] , \vimm_o[42] , \vimm_o[43] , \vimm_o[44] , \vimm_o[45] , \vimm_o[46] , \vimm_o[47] , \vimm_o[48] , \vimm_o[49] , \vimm_o[50] , \vimm_o[51] 
, \vimm_o[52] , \vimm_o[53] , \vimm_o[54] , \vimm_o[55] , \vimm_o[56] , \vimm_o[57] , \vimm_o[58] , \vimm_o[59] , \vimm_o[60] , \vimm_o[61] , \vimm_o[62] , \vimm_o[63] );
  input \inst_i[0] ;
  wire \inst_i[0] ;
  input \inst_i[1] ;
  wire \inst_i[1] ;
  input \inst_i[2] ;
  wire \inst_i[2] ;
  input \inst_i[3] ;
  wire \inst_i[3] ;
  input \inst_i[4] ;
  wire \inst_i[4] ;
  input \inst_i[5] ;
  wire \inst_i[5] ;
  input \inst_i[6] ;
  wire \inst_i[6] ;
  input \inst_i[7] ;
  wire \inst_i[7] ;
  input \inst_i[8] ;
  wire \inst_i[8] ;
  input \inst_i[9] ;
  wire \inst_i[9] ;
  input \inst_i[10] ;
  wire \inst_i[10] ;
  input \inst_i[11] ;
  wire \inst_i[11] ;
  input \inst_i[12] ;
  wire \inst_i[12] ;
  input \inst_i[13] ;
  wire \inst_i[13] ;
  input \inst_i[14] ;
  wire \inst_i[14] ;
  input \inst_i[15] ;
  wire \inst_i[15] ;
  input \inst_i[16] ;
  wire \inst_i[16] ;
  input \inst_i[17] ;
  wire \inst_i[17] ;
  input \inst_i[18] ;
  wire \inst_i[18] ;
  input \inst_i[19] ;
  wire \inst_i[19] ;
  input \inst_i[20] ;
  wire \inst_i[20] ;
  input \inst_i[21] ;
  wire \inst_i[21] ;
  input \inst_i[22] ;
  wire \inst_i[22] ;
  input \inst_i[23] ;
  wire \inst_i[23] ;
  input \inst_i[24] ;
  wire \inst_i[24] ;
  input \inst_i[25] ;
  wire \inst_i[25] ;
  input \inst_i[26] ;
  wire \inst_i[26] ;
  input \inst_i[27] ;
  wire \inst_i[27] ;
  input \inst_i[28] ;
  wire \inst_i[28] ;
  input \inst_i[29] ;
  wire \inst_i[29] ;
  input \inst_i[30] ;
  wire \inst_i[30] ;
  input \inst_i[31] ;
  wire \inst_i[31] ;
  output \vimm_o[0] ;
  wire \vimm_o[0] ;
  output \vimm_o[1] ;
  wire \vimm_o[1] ;
  output \vimm_o[2] ;
  wire \vimm_o[2] ;
  output \vimm_o[3] ;
  wire \vimm_o[3] ;
  output \vimm_o[4] ;
  wire \vimm_o[4] ;
  output \vimm_o[5] ;
  wire \vimm_o[5] ;
  output \vimm_o[6] ;
  wire \vimm_o[6] ;
  output \vimm_o[7] ;
  wire \vimm_o[7] ;
  output \vimm_o[8] ;
  wire \vimm_o[8] ;
  output \vimm_o[9] ;
  wire \vimm_o[9] ;
  output \vimm_o[10] ;
  wire \vimm_o[10] ;
  output \vimm_o[11] ;
  wire \vimm_o[11] ;
  output \vimm_o[12] ;
  wire \vimm_o[12] ;
  output \vimm_o[13] ;
  wire \vimm_o[13] ;
  output \vimm_o[14] ;
  wire \vimm_o[14] ;
  output \vimm_o[15] ;
  wire \vimm_o[15] ;
  output \vimm_o[16] ;
  wire \vimm_o[16] ;
  output \vimm_o[17] ;
  wire \vimm_o[17] ;
  output \vimm_o[18] ;
  wire \vimm_o[18] ;
  output \vimm_o[19] ;
  wire \vimm_o[19] ;
  output \vimm_o[20] ;
  wire \vimm_o[20] ;
  output \vimm_o[21] ;
  wire \vimm_o[21] ;
  output \vimm_o[22] ;
  wire \vimm_o[22] ;
  output \vimm_o[23] ;
  wire \vimm_o[23] ;
  output \vimm_o[24] ;
  wire \vimm_o[24] ;
  output \vimm_o[25] ;
  wire \vimm_o[25] ;
  output \vimm_o[26] ;
  wire \vimm_o[26] ;
  output \vimm_o[27] ;
  wire \vimm_o[27] ;
  output \vimm_o[28] ;
  wire \vimm_o[28] ;
  output \vimm_o[29] ;
  wire \vimm_o[29] ;
  output \vimm_o[30] ;
  wire \vimm_o[30] ;
  output \vimm_o[31] ;
  wire \vimm_o[31] ;
  output \vimm_o[32] ;
  wire \vimm_o[32] ;
  output \vimm_o[33] ;
  wire \vimm_o[33] ;
  output \vimm_o[34] ;
  wire \vimm_o[34] ;
  output \vimm_o[35] ;
  wire \vimm_o[35] ;
  output \vimm_o[36] ;
  wire \vimm_o[36] ;
  output \vimm_o[37] ;
  wire \vimm_o[37] ;
  output \vimm_o[38] ;
  wire \vimm_o[38] ;
  output \vimm_o[39] ;
  wire \vimm_o[39] ;
  output \vimm_o[40] ;
  wire \vimm_o[40] ;
  output \vimm_o[41] ;
  wire \vimm_o[41] ;
  output \vimm_o[42] ;
  wire \vimm_o[42] ;
  output \vimm_o[43] ;
  wire \vimm_o[43] ;
  output \vimm_o[44] ;
  wire \vimm_o[44] ;
  output \vimm_o[45] ;
  wire \vimm_o[45] ;
  output \vimm_o[46] ;
  wire \vimm_o[46] ;
  output \vimm_o[47] ;
  wire \vimm_o[47] ;
  output \vimm_o[48] ;
  wire \vimm_o[48] ;
  output \vimm_o[49] ;
  wire \vimm_o[49] ;
  output \vimm_o[50] ;
  wire \vimm_o[50] ;
  output \vimm_o[51] ;
  wire \vimm_o[51] ;
  output \vimm_o[52] ;
  wire \vimm_o[52] ;
  output \vimm_o[53] ;
  wire \vimm_o[53] ;
  output \vimm_o[54] ;
  wire \vimm_o[54] ;
  output \vimm_o[55] ;
  wire \vimm_o[55] ;
  output \vimm_o[56] ;
  wire \vimm_o[56] ;
  output \vimm_o[57] ;
  wire \vimm_o[57] ;
  output \vimm_o[58] ;
  wire \vimm_o[58] ;
  output \vimm_o[59] ;
  wire \vimm_o[59] ;
  output \vimm_o[60] ;
  wire \vimm_o[60] ;
  output \vimm_o[61] ;
  wire \vimm_o[61] ;
  output \vimm_o[62] ;
  wire \vimm_o[62] ;
  output \vimm_o[63] ;
  wire \vimm_o[63] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  INV_X1 _11_ (
    .A(\inst_i[5] ),
    .ZN(_00_)
  );
  INV_X1 _12_ (
    .A(\inst_i[3] ),
    .ZN(_01_)
  );
  INV_X1 _13_ (
    .A(\inst_i[14] ),
    .ZN(_02_)
  );
  INV_X1 _14_ (
    .A(\inst_i[18] ),
    .ZN(_03_)
  );
  INV_X1 _15_ (
    .A(\inst_i[17] ),
    .ZN(_04_)
  );
  INV_X1 _16_ (
    .A(\inst_i[16] ),
    .ZN(_05_)
  );
  INV_X1 _17_ (
    .A(\inst_i[19] ),
    .ZN(_06_)
  );
  INV_X1 _18_ (
    .A(\inst_i[15] ),
    .ZN(_07_)
  );
  NAND3_X1 _19_ (
    .A1(\inst_i[0] ),
    .A2(\inst_i[6] ),
    .A3(_01_),
    .ZN(_08_)
  );
  NAND4_X1 _20_ (
    .A1(\inst_i[1] ),
    .A2(_00_),
    .A3(\inst_i[4] ),
    .A4(\inst_i[2] ),
    .ZN(_09_)
  );
  NAND3_X1 _21_ (
    .A1(\inst_i[13] ),
    .A2(_02_),
    .A3(\inst_i[12] ),
    .ZN(_10_)
  );
  NOR4_X1 _22_ (
    .A1(_03_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(\vimm_o[11] )
  );
  NOR4_X1 _23_ (
    .A1(_04_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(\vimm_o[10] )
  );
  NOR4_X1 _24_ (
    .A1(_05_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(\vimm_o[17] )
  );
  NOR4_X1 _25_ (
    .A1(_06_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(\vimm_o[12] )
  );
  NOR4_X1 _26_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(\vimm_o[0] )
  );
  assign \vimm_o[60]  = \vimm_o[12] ;
  assign \vimm_o[59]  = \vimm_o[11] ;
  assign \vimm_o[58]  = \vimm_o[10] ;
  assign \vimm_o[57]  = \vimm_o[17] ;
  assign \vimm_o[56]  = \vimm_o[0] ;
  assign \vimm_o[55]  = \vimm_o[12] ;
  assign \vimm_o[54]  = \vimm_o[12] ;
  assign \vimm_o[53]  = \vimm_o[12] ;
  assign \vimm_o[52]  = \vimm_o[12] ;
  assign \vimm_o[51]  = \vimm_o[11] ;
  assign \vimm_o[50]  = \vimm_o[10] ;
  assign \vimm_o[49]  = \vimm_o[17] ;
  assign \vimm_o[48]  = \vimm_o[0] ;
  assign \vimm_o[47]  = \vimm_o[12] ;
  assign \vimm_o[46]  = \vimm_o[12] ;
  assign \vimm_o[45]  = \vimm_o[12] ;
  assign \vimm_o[44]  = \vimm_o[12] ;
  assign \vimm_o[43]  = \vimm_o[11] ;
  assign \vimm_o[42]  = \vimm_o[10] ;
  assign \vimm_o[41]  = \vimm_o[17] ;
  assign \vimm_o[40]  = \vimm_o[0] ;
  assign \vimm_o[39]  = \vimm_o[12] ;
  assign \vimm_o[38]  = \vimm_o[12] ;
  assign \vimm_o[37]  = \vimm_o[12] ;
  assign \vimm_o[36]  = \vimm_o[12] ;
  assign \vimm_o[35]  = \vimm_o[11] ;
  assign \vimm_o[34]  = \vimm_o[10] ;
  assign \vimm_o[33]  = \vimm_o[17] ;
  assign \vimm_o[32]  = \vimm_o[0] ;
  assign \vimm_o[31]  = \vimm_o[12] ;
  assign \vimm_o[30]  = \vimm_o[12] ;
  assign \vimm_o[29]  = \vimm_o[12] ;
  assign \vimm_o[28]  = \vimm_o[12] ;
  assign \vimm_o[27]  = \vimm_o[11] ;
  assign \vimm_o[26]  = \vimm_o[10] ;
  assign \vimm_o[25]  = \vimm_o[17] ;
  assign \vimm_o[24]  = \vimm_o[0] ;
  assign \vimm_o[23]  = \vimm_o[12] ;
  assign \vimm_o[22]  = \vimm_o[12] ;
  assign \vimm_o[21]  = \vimm_o[12] ;
  assign \vimm_o[20]  = \vimm_o[12] ;
  assign \vimm_o[19]  = \vimm_o[11] ;
  assign \vimm_o[18]  = \vimm_o[10] ;
  assign \vimm_o[16]  = \vimm_o[0] ;
  assign \vimm_o[15]  = \vimm_o[12] ;
  assign \vimm_o[14]  = \vimm_o[12] ;
  assign \vimm_o[13]  = \vimm_o[12] ;
  assign \vimm_o[9]  = \vimm_o[17] ;
  assign \vimm_o[8]  = \vimm_o[0] ;
  assign \vimm_o[7]  = \vimm_o[12] ;
  assign \vimm_o[6]  = \vimm_o[12] ;
  assign \vimm_o[5]  = \vimm_o[12] ;
  assign \vimm_o[4]  = \vimm_o[12] ;
  assign \vimm_o[3]  = \vimm_o[11] ;
  assign \vimm_o[2]  = \vimm_o[10] ;
  assign \vimm_o[1]  = \vimm_o[17] ;
  assign \vimm_o[61]  = \vimm_o[12] ;
  assign \vimm_o[62]  = \vimm_o[12] ;
  assign \vimm_o[63]  = \vimm_o[12] ;
endmodule
