/* Generated by Yosys 0.65+57 (git sha1 9d0cdb855, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module vector_control(i_clk, ni_rst, \inst[0] , \inst[1] , \inst[2] , \inst[3] , \inst[4] , \inst[5] , \inst[6] , \inst[7] , \inst[8] , \inst[9] , \inst[10] , \inst[11] , \inst[12] , \inst[13] , \inst[14] , \inst[15] , \inst[16] , \inst[17] , \inst[18] 
, \inst[19] , \inst[20] , \inst[21] , \inst[22] , \inst[23] , \inst[24] , \inst[25] , \inst[26] , \inst[27] , \inst[28] , \inst[29] , \inst[30] , \inst[31] , vector_enb, is_vsetvli, valu_unsign, vector_wb, \vop1_sel[0] , \vop1_sel[1] , \valu_opcode[0] , \valu_opcode[1] 
, \valu_opcode[2] , \valu_opcode[3] , memv_rden, vector_wren, memv_wren);
  input i_clk;
  wire i_clk;
  input ni_rst;
  wire ni_rst;
  input \inst[0] ;
  wire \inst[0] ;
  input \inst[1] ;
  wire \inst[1] ;
  input \inst[2] ;
  wire \inst[2] ;
  input \inst[3] ;
  wire \inst[3] ;
  input \inst[4] ;
  wire \inst[4] ;
  input \inst[5] ;
  wire \inst[5] ;
  input \inst[6] ;
  wire \inst[6] ;
  input \inst[7] ;
  wire \inst[7] ;
  input \inst[8] ;
  wire \inst[8] ;
  input \inst[9] ;
  wire \inst[9] ;
  input \inst[10] ;
  wire \inst[10] ;
  input \inst[11] ;
  wire \inst[11] ;
  input \inst[12] ;
  wire \inst[12] ;
  input \inst[13] ;
  wire \inst[13] ;
  input \inst[14] ;
  wire \inst[14] ;
  input \inst[15] ;
  wire \inst[15] ;
  input \inst[16] ;
  wire \inst[16] ;
  input \inst[17] ;
  wire \inst[17] ;
  input \inst[18] ;
  wire \inst[18] ;
  input \inst[19] ;
  wire \inst[19] ;
  input \inst[20] ;
  wire \inst[20] ;
  input \inst[21] ;
  wire \inst[21] ;
  input \inst[22] ;
  wire \inst[22] ;
  input \inst[23] ;
  wire \inst[23] ;
  input \inst[24] ;
  wire \inst[24] ;
  input \inst[25] ;
  wire \inst[25] ;
  input \inst[26] ;
  wire \inst[26] ;
  input \inst[27] ;
  wire \inst[27] ;
  input \inst[28] ;
  wire \inst[28] ;
  input \inst[29] ;
  wire \inst[29] ;
  input \inst[30] ;
  wire \inst[30] ;
  input \inst[31] ;
  wire \inst[31] ;
  input vector_enb;
  wire vector_enb;
  input is_vsetvli;
  wire is_vsetvli;
  output valu_unsign;
  wire valu_unsign;
  output vector_wb;
  wire vector_wb;
  output \vop1_sel[0] ;
  wire \vop1_sel[0] ;
  output \vop1_sel[1] ;
  wire \vop1_sel[1] ;
  output \valu_opcode[0] ;
  wire \valu_opcode[0] ;
  output \valu_opcode[1] ;
  wire \valu_opcode[1] ;
  output \valu_opcode[2] ;
  wire \valu_opcode[2] ;
  output \valu_opcode[3] ;
  wire \valu_opcode[3] ;
  output memv_rden;
  wire memv_rden;
  output vector_wren;
  wire vector_wren;
  output memv_wren;
  wire memv_wren;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  INV_X1 _075_ (
    .A(vector_enb),
    .ZN(_010_)
  );
  INV_X1 _076_ (
    .A(is_vsetvli),
    .ZN(_011_)
  );
  INV_X1 _077_ (
    .A(\inst[3] ),
    .ZN(_012_)
  );
  INV_X1 _078_ (
    .A(\inst[5] ),
    .ZN(_013_)
  );
  INV_X1 _079_ (
    .A(\inst[12] ),
    .ZN(_014_)
  );
  INV_X1 _080_ (
    .A(\inst[13] ),
    .ZN(_015_)
  );
  INV_X1 _081_ (
    .A(\inst[14] ),
    .ZN(_016_)
  );
  INV_X1 _082_ (
    .A(\inst[26] ),
    .ZN(_017_)
  );
  INV_X1 _083_ (
    .A(\inst[27] ),
    .ZN(_018_)
  );
  INV_X1 _084_ (
    .A(\inst[31] ),
    .ZN(_019_)
  );
  AND4_X1 _085_ (
    .A1(\inst[2] ),
    .A2(_012_),
    .A3(\inst[1] ),
    .A4(\inst[0] ),
    .ZN(_020_)
  );
  AND3_X1 _086_ (
    .A1(\inst[6] ),
    .A2(\inst[4] ),
    .A3(_013_),
    .ZN(_021_)
  );
  NAND2_X1 _087_ (
    .A1(_020_),
    .A2(_021_),
    .ZN(_022_)
  );
  NOR3_X1 _088_ (
    .A1(_014_),
    .A2(_015_),
    .A3(\inst[14] ),
    .ZN(_023_)
  );
  NAND3_X1 _089_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_023_),
    .ZN(_024_)
  );
  INV_X1 _090_ (
    .A(_024_),
    .ZN(_025_)
  );
  NOR2_X1 _091_ (
    .A1(\inst[12] ),
    .A2(\inst[13] ),
    .ZN(_026_)
  );
  NAND3_X1 _092_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_026_),
    .ZN(_027_)
  );
  OAI211_X1 _093_ (
    .A(_020_),
    .B(_021_),
    .C1(_023_),
    .C2(_026_),
    .ZN(_028_)
  );
  NAND2_X1 _094_ (
    .A1(vector_enb),
    .A2(_011_),
    .ZN(_029_)
  );
  NOR2_X1 _095_ (
    .A1(_028_),
    .A2(_029_),
    .ZN(_030_)
  );
  AND2_X1 _096_ (
    .A1(\inst[26] ),
    .A2(\inst[29] ),
    .ZN(_031_)
  );
  NOR2_X1 _097_ (
    .A1(\inst[28] ),
    .A2(\inst[27] ),
    .ZN(_032_)
  );
  NAND2_X1 _098_ (
    .A1(\inst[31] ),
    .A2(_032_),
    .ZN(_033_)
  );
  INV_X1 _099_ (
    .A(_033_),
    .ZN(_034_)
  );
  AOI21_X1 _100_ (
    .A(_033_),
    .B1(_031_),
    .B2(_024_),
    .ZN(_035_)
  );
  AND2_X1 _101_ (
    .A1(_031_),
    .A2(_032_),
    .ZN(_036_)
  );
  NOR2_X1 _102_ (
    .A1(_035_),
    .A2(_036_),
    .ZN(_037_)
  );
  NOR2_X1 _103_ (
    .A1(_017_),
    .A2(\inst[29] ),
    .ZN(_038_)
  );
  NAND4_X1 _104_ (
    .A1(\inst[28] ),
    .A2(_018_),
    .A3(\inst[31] ),
    .A4(_038_),
    .ZN(_039_)
  );
  NOR2_X1 _105_ (
    .A1(\inst[28] ),
    .A2(_018_),
    .ZN(_040_)
  );
  NOR4_X1 _106_ (
    .A1(\inst[28] ),
    .A2(_018_),
    .A3(\inst[29] ),
    .A4(_019_),
    .ZN(_041_)
  );
  INV_X1 _107_ (
    .A(_041_),
    .ZN(_042_)
  );
  OAI21_X1 _108_ (
    .A(_039_),
    .B1(_042_),
    .B2(_027_),
    .ZN(_043_)
  );
  INV_X1 _109_ (
    .A(_043_),
    .ZN(_044_)
  );
  AOI211_X1 _110_ (
    .A(_028_),
    .B(_029_),
    .C1(_037_),
    .C2(_044_),
    .ZN(\valu_opcode[2] )
  );
  NAND3_X1 _111_ (
    .A1(\inst[29] ),
    .A2(_019_),
    .A3(_040_),
    .ZN(_045_)
  );
  NAND2_X1 _112_ (
    .A1(\inst[31] ),
    .A2(_036_),
    .ZN(_046_)
  );
  NOR3_X1 _113_ (
    .A1(\inst[26] ),
    .A2(\inst[29] ),
    .A3(\inst[31] ),
    .ZN(_047_)
  );
  NOR2_X1 _114_ (
    .A1(\inst[29] ),
    .A2(\inst[31] ),
    .ZN(_048_)
  );
  NAND2_X1 _115_ (
    .A1(\inst[28] ),
    .A2(_047_),
    .ZN(_049_)
  );
  NAND4_X1 _116_ (
    .A1(_014_),
    .A2(_015_),
    .A3(_020_),
    .A4(_021_),
    .ZN(_050_)
  );
  NAND2_X1 _117_ (
    .A1(_024_),
    .A2(_050_),
    .ZN(_051_)
  );
  AOI21_X1 _118_ (
    .A(_045_),
    .B1(_050_),
    .B2(_024_),
    .ZN(_052_)
  );
  AOI21_X1 _119_ (
    .A(_050_),
    .B1(_049_),
    .B2(_046_),
    .ZN(_053_)
  );
  AOI211_X1 _120_ (
    .A(_052_),
    .B(_053_),
    .C1(_035_),
    .C2(_051_),
    .ZN(_054_)
  );
  OAI21_X1 _121_ (
    .A(_011_),
    .B1(_054_),
    .B2(_010_),
    .ZN(\valu_opcode[1] )
  );
  AOI22_X1 _122_ (
    .A1(\inst[31] ),
    .A2(_036_),
    .B1(_047_),
    .B2(_032_),
    .ZN(_055_)
  );
  OAI211_X1 _123_ (
    .A(_039_),
    .B(_055_),
    .C1(_045_),
    .C2(\inst[26] ),
    .ZN(_056_)
  );
  OAI21_X1 _124_ (
    .A(_056_),
    .B1(_026_),
    .B2(_023_),
    .ZN(_057_)
  );
  AND3_X1 _125_ (
    .A1(\inst[28] ),
    .A2(\inst[27] ),
    .A3(_048_),
    .ZN(_058_)
  );
  OAI21_X1 _126_ (
    .A(_026_),
    .B1(_041_),
    .B2(_058_),
    .ZN(_059_)
  );
  AOI211_X1 _127_ (
    .A(_022_),
    .B(_029_),
    .C1(_057_),
    .C2(_059_),
    .ZN(\valu_opcode[0] )
  );
  NOR2_X1 _128_ (
    .A1(\inst[6] ),
    .A2(\inst[4] ),
    .ZN(_060_)
  );
  AND2_X1 _129_ (
    .A1(_020_),
    .A2(_060_),
    .ZN(_061_)
  );
  NOR2_X1 _130_ (
    .A1(_016_),
    .A2(_027_),
    .ZN(_062_)
  );
  NOR4_X1 _131_ (
    .A1(is_vsetvli),
    .A2(_025_),
    .A3(_061_),
    .A4(_062_),
    .ZN(\vop1_sel[0] )
  );
  AND3_X1 _132_ (
    .A1(_011_),
    .A2(_013_),
    .A3(_061_),
    .ZN(memv_rden)
  );
  NOR2_X1 _133_ (
    .A1(is_vsetvli),
    .A2(_028_),
    .ZN(_063_)
  );
  OR2_X1 _134_ (
    .A1(memv_rden),
    .A2(_063_),
    .ZN(vector_wren)
  );
  AND3_X1 _135_ (
    .A1(_011_),
    .A2(\inst[5] ),
    .A3(_061_),
    .ZN(memv_wren)
  );
  NOR2_X1 _136_ (
    .A1(\inst[14] ),
    .A2(_027_),
    .ZN(_064_)
  );
  OAI21_X1 _137_ (
    .A(_024_),
    .B1(_027_),
    .B2(\inst[14] ),
    .ZN(_065_)
  );
  NOR2_X1 _138_ (
    .A1(\inst[29] ),
    .A2(_033_),
    .ZN(_066_)
  );
  NOR3_X1 _139_ (
    .A1(\inst[26] ),
    .A2(\inst[29] ),
    .A3(_033_),
    .ZN(_067_)
  );
  OAI21_X1 _140_ (
    .A(_017_),
    .B1(_027_),
    .B2(_016_),
    .ZN(_068_)
  );
  NOR3_X1 _141_ (
    .A1(\inst[29] ),
    .A2(_028_),
    .A3(_033_),
    .ZN(_069_)
  );
  AND3_X1 _142_ (
    .A1(\inst[28] ),
    .A2(_018_),
    .A3(_019_),
    .ZN(_070_)
  );
  AND2_X1 _143_ (
    .A1(_038_),
    .A2(_070_),
    .ZN(_071_)
  );
  AOI211_X1 _144_ (
    .A(_041_),
    .B(_058_),
    .C1(_070_),
    .C2(_038_),
    .ZN(_072_)
  );
  AOI21_X1 _145_ (
    .A(_027_),
    .B1(_049_),
    .B2(_072_),
    .ZN(_073_)
  );
  AOI221_X1 _146_ (
    .A(_073_),
    .B1(_069_),
    .B2(_068_),
    .C1(_065_),
    .C2(_067_),
    .ZN(_074_)
  );
  OAI21_X1 _147_ (
    .A(_011_),
    .B1(_074_),
    .B2(_010_),
    .ZN(\valu_opcode[3] )
  );
  NOR2_X1 _148_ (
    .A1(is_vsetvli),
    .A2(_024_),
    .ZN(\vop1_sel[1] )
  );
  OAI21_X1 _149_ (
    .A(_040_),
    .B1(_047_),
    .B2(_038_),
    .ZN(_000_)
  );
  AOI21_X1 _150_ (
    .A(_071_),
    .B1(_047_),
    .B2(_032_),
    .ZN(_001_)
  );
  OAI21_X1 _151_ (
    .A(\inst[26] ),
    .B1(_034_),
    .B2(_058_),
    .ZN(_002_)
  );
  NAND4_X1 _152_ (
    .A1(_062_),
    .A2(_000_),
    .A3(_001_),
    .A4(_002_),
    .ZN(_003_)
  );
  AOI21_X1 _153_ (
    .A(_071_),
    .B1(_047_),
    .B2(_040_),
    .ZN(_004_)
  );
  NOR4_X1 _154_ (
    .A1(_017_),
    .A2(\inst[28] ),
    .A3(\inst[29] ),
    .A4(_019_),
    .ZN(_005_)
  );
  AOI21_X1 _155_ (
    .A(_005_),
    .B1(_058_),
    .B2(\inst[26] ),
    .ZN(_006_)
  );
  NAND4_X1 _156_ (
    .A1(_055_),
    .A2(_064_),
    .A3(_004_),
    .A4(_006_),
    .ZN(_007_)
  );
  AOI21_X1 _157_ (
    .A(_066_),
    .B1(_048_),
    .B2(_040_),
    .ZN(_008_)
  );
  OAI211_X1 _158_ (
    .A(_027_),
    .B(_055_),
    .C1(_008_),
    .C2(_017_),
    .ZN(_009_)
  );
  NAND4_X1 _159_ (
    .A1(_030_),
    .A2(_003_),
    .A3(_007_),
    .A4(_009_),
    .ZN(valu_unsign)
  );
  assign vector_wb = memv_rden;
endmodule
